# Generated by Django 2.2.2 on 2019-06-05 19:03

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/moggers/workspace/django-sendfile2/examples/protected_downloads/protected'), upload_to='download')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
